name: resusable-workflow-caller

on:
  push:
    branches: none 
  pull_request:
    branches: none 

  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: simran-makhijaaa/scriptrepo.github/workflows/final.yaml@main
    with:
      username: simran
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-B:
    uses: simran-makhijaaa/scriptrepo.github/workflows/final.yaml@main
    with:
      username: simran2
    secrets:
      token: ${{ secrets.TOKEN }}
  
